library(LaplacesDemon)
library(mvtnorm)

#source('bayesian_bridge_adp.R')
#source('bayesian_bridge_adp_HMC.R')
source('second_order.R')
source('bayesian_bridge_adp_convergence.R')
source('bayesian_bridge_adp_HMC_convergence.R')
source('predict.R')
source('predict_c.R')
source('metropolis.R')
source('otlcircuit.R')
#source('camel6.R')
#source('sumpow.R')
#source('wingweight.R')
source('piston.R')

source('leapfrog.R')
source('init_eps.R')
source('dual_avg.R')
source('adp_SphHMC.R')
source('leapfrog_HMC.R')
source('init_eps_HMC.R')
source('adp_HMC.R')

source('bayesian_bridge_test.R')
source('bayesian_linear_test.R')